
package abstracfactory;

import javax.swing.JOptionPane;

/**
 *
 * @author TheChay
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    
    public frmPrincipal() {
        initComponents();
        txtRadio.setVisible(false);
        txtLado.setVisible(false);
        txtAltura.setVisible(false);
        lblRadio.setVisible(false);
        lblLado.setVisible(false);
        lblAltura.setVisible(false);
        
    }
    float valores[];
    Ifigura circulo = fabrica.fabricar("circulo");
    Ifigura cuadrado = fabrica.fabricar("cuadrado");
    Ifigura rectangulo = fabrica.fabricar("rectangulo");
    Ifigura triangulo = fabrica.fabricar("triangulo");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbFiguras = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        btnPerimetro = new javax.swing.JButton();
        btnDescripcion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        txtLado = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        lblRadio = new javax.swing.JLabel();
        lblLado = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FIGURAS");

        cmbFiguras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Circulo", "Cuadrado", "Rectangulo", "Triangulo", " " }));
        cmbFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFigurasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccionar Figura:");

        btnArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnArea.setText("Área");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnPerimetro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPerimetro.setText("Perímetro");
        btnPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroActionPerformed(evt);
            }
        });

        btnDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDescripcion.setText("Descripción");
        btnDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescripcionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Calcular:");

        lblRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRadio.setText("Radio:");

        lblLado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLado.setText("Lado:");

        lblAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltura.setText("Altura:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPerimetro)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnDescripcion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRadio)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblAltura)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAltura))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblLado)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado)
                    .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltura))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArea)
                    .addComponent(btnPerimetro)
                    .addComponent(btnDescripcion))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFigurasActionPerformed

        switch (cmbFiguras.getSelectedIndex()) {
            case 0: //
                txtRadio.setVisible(true);
                txtLado.setVisible(false);
                txtAltura.setVisible(false);
                lblRadio.setVisible(true);
                lblLado.setVisible(false);
                lblAltura.setVisible(false);

                break;
            case 1: //Cuadrado
                txtRadio.setVisible(false);
                txtLado.setVisible(true);
                txtAltura.setVisible(false);
                lblRadio.setVisible(false);
                lblLado.setVisible(true);
                lblAltura.setVisible(false);
                break;
            case 2: //Rectangulo
                txtRadio.setVisible(false);
                txtLado.setVisible(true);
                txtAltura.setVisible(true);
                lblRadio.setVisible(false);
                lblLado.setText("Base:");
                lblLado.setVisible(true);
                lblAltura.setVisible(true);
                break;
            case 3: // Triangulo
                txtRadio.setVisible(false);
                txtLado.setVisible(true);
                txtAltura.setVisible(true);
                lblRadio.setVisible(false);
                lblLado.setVisible(true);
                lblLado.setText("Base:");
                lblAltura.setVisible(true);
                break;
        }

    }//GEN-LAST:event_cmbFigurasActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        switch (cmbFiguras.getSelectedIndex()) {
            case 0: // Circulo      
                valores = new float[2];
                valores[0] = Float.parseFloat(txtRadio.getText());
                circulo.inicio(valores);
                JOptionPane.showMessageDialog(null, circulo.area());
                break;
            case 1: //Cuadrado
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                cuadrado.inicio(valores);
                JOptionPane.showMessageDialog(null, cuadrado.area());
                break;
            case 2: //Rectangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                rectangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, rectangulo.area());
                break;
            case 3: // Triangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                triangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, triangulo.area());
                break;
        }
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroActionPerformed
        switch (cmbFiguras.getSelectedIndex()) {
            case 0: // Circulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtRadio.getText());
                circulo.inicio(valores);
                JOptionPane.showMessageDialog(null, circulo.perimetro());
                break;
            case 1: //Cuadrado
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                cuadrado.inicio(valores);
                JOptionPane.showMessageDialog(null, cuadrado.perimetro());
                break;
            case 2: //Rectangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                rectangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, rectangulo.perimetro());
                break;
            case 3: // Triangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                triangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, triangulo.perimetro());
                break;
        }
    }//GEN-LAST:event_btnPerimetroActionPerformed

    private void btnDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescripcionActionPerformed
        
        switch (cmbFiguras.getSelectedIndex()) {
            case 0: // Circulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtRadio.getText());
                circulo.inicio(valores);
                JOptionPane.showMessageDialog(null, circulo.descripcion());
                break;
            case 1: //Cuadrado
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                cuadrado.inicio(valores);
                JOptionPane.showMessageDialog(null, cuadrado.descripcion());
                break;
            case 2: //Rectangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                rectangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, rectangulo.descripcion());
                break;
            case 3: // Triangulo
                valores = new float[2];
                valores[0] = Float.parseFloat(txtLado.getText());
                valores[1] = Float.parseFloat(txtAltura.getText());
                triangulo.inicio(valores);
                JOptionPane.showMessageDialog(null, triangulo.descripcion());
                break;
        }
    }//GEN-LAST:event_btnDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnDescripcion;
    private javax.swing.JButton btnPerimetro;
    private javax.swing.JComboBox<String> cmbFiguras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblLado;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
